name: Deploy Cosmos UI (Github Pages)
run-name: Frontend Deploy by @${{ github.actor }} 🚀

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

concurrency:
  group: "cross-repo-pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angular

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Install Frontend Dependencies
        run: pnpm install

      - name: Build Application (Production Payload)
        run: pnpm run build --configuration production

      - name: Fix SPA Routing (Copy index.html to 404.html)
        run: cp ./dist/angular/browser/index.html ./dist/angular/browser/404.html

      - name: Deploy Payload to Portfolio Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_PAT_TOKEN }}
          external_repository: SandeepSagarPanjala/SandeepSagarPanjala.github.io
          publish_branch: develop
          # Note: We still use the full path here because 'uses' steps don't follow 'defaults'
          publish_dir: ./angular/dist/angular/browser
          cname: sandeepsagar.work
          force_orphan: true
